// vue/shoppinglist/src/components/ShoppingList.vue
<template>
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Type</th>
				<th>Count</th>
				<th>Price</th>			
			</tr>
		</thead>
		<tbody>
			<tr v-for="item in list" :key="item.id">
				<td>{{item.type}}</td>
				<td>{{item.count}}</td>
				<td>{{item.price}}</td>
			</tr>
		</tbody>
	</table>
</template>
<script>
export default {
	name:"ShoppingList",
	props:['list']
}
</script>

// react/hooks-3-alltogether/frontend/src/components/ShoppingList.js
import React from 'react';
import {Table,Button} from 'semantic-ui-react';

const ShoppingList = ({list,removeFromList}) => {
	
	let items = list.map((item,index) => {
		return <Table.Row key={index}>
					<Table.Cell>{item.type}</Table.Cell>
					<Table.Cell>{item.count}</Table.Cell>
					<Table.Cell>{item.price}</Table.Cell>
					<Table.Cell><Button onClick={()=>removeFromList(item.id)}>Remove</Button></Table.Cell>
				</Table.Row>		
	})
	
	return (
		<Table celled>
			<Table.Header>
				<Table.Row>
					<Table.HeaderCell>Type</Table.HeaderCell>
					<Table.HeaderCell>Count</Table.HeaderCell>
					<Table.HeaderCell>Price</Table.HeaderCell>
					<Table.HeaderCell>Remove</Table.HeaderCell>
				</Table.Row>
			</Table.Header>
			<Table.Body>
				{items}
			</Table.Body>
		</Table>
	)
	
}

export default ShoppingList;
