// react/reduxtest/src/components/ShoppingForm.js
import React from 'react';
import {Form,Button} from 'semantic-ui-react';
import {connect} from 'react-redux';

class ShoppingForm extends React.Component {
	constructor(props) {
		super(props);
		this.state = {
			type:"",
			price:0,
			count:0
		}
		
	}
	
	onSubmit = event => {
		event.preventDefault();
		let item = {
			type:this.state.type,
			price:this.state.price,
			count:this.state.count
		}
		this.props.dispatch({
			type:"ADD_TO_LIST",
			item:item
		})
	}
	
	onChange = event => {
		let state = {};
		state[event.target.name] = event.target.value;
		this.setState(state);
	}

	render() {
		return(
			<Form onSubmit={this.onSubmit}>
				<Form.Field>
					<label htmlFor="type">Item Type:</label>
					<input type="text"
						   name="type"
						   onChange={this.onChange}
						   value={this.state.type}/>
				</Form.Field>
				<Form.Field>
					<label htmlFor="price">Item Price:</label>
					<input type="number"
						   name="price"
						   onChange={this.onChange}
						   value={this.state.price}/>
				</Form.Field>
				<Form.Field>
					<label htmlFor="count">Number of Items:</label>
					<input type="number"
						   name="count"
						   onChange={this.onChange}
						   value={this.state.count}/>
				</Form.Field>
				<Button type="submit">Add</Button>
			</Form>
		)
	}

}

export default connect()(ShoppingForm);

// vue/shoppinglistvuex/src/views/ShoppingForm.vue
<template>
	<div>
		<div class="form form-group">
			<label for="type">Type:</label>
			<input type="text"
					name="type"
					v-model="item.type"/>
		</div>
		<div class="form form-group">
			<label for="price">Price:</label>
			<input type="number"
					name="price"
					v-model="item.price"
					min="0"
					step="0.01"/>
		</div>
		<div class="form form-group">
			<label for="count">Count:</label>
			<input type="number"
					name="count"
					v-model="item.count"
					min="0"/>
		</div>
		<button class="btn btn-primary" v-on:click="addToList()">Add</button>
	</div>
</template>
<script>
export default {
	name:"ShoppingForm",
	data() {
		return {
			item: {
				id:0,
				type:"",
				price:0,
				count:0			
			}
		}
	},
	methods: {
		addToList:function() {
			this.$store.dispatch("addToList",this.item);
			this.item = {
				id:0,
				type:"",
				price:0,
				count:0			
			}
			this.$router.push("/");
		}
	}
}

</script>
