// vue/shoppinglist/src/components/ShoppingForm.vue
<template>
	<div>
		<div class="form form-group">
			<label for="type">Type:</label>
			<input type="text"
					name="type"
					v-model="item.type"/>
		</div>
		<div class="form form-group">
			<label for="price">Price:</label>
			<input type="number"
					name="price"
					v-model="item.price"
					min="0"
					step="0.01"/>
		</div>
		<div class="form form-group">
			<label for="count">Count:</label>
			<input type="number"
					name="count"
					v-model="item.count"
					min="0"/>
		</div>
		<button class="btn btn-primary" v-on:click="addToList()">Add</button>
	</div>
</template>
<script>
export default {
	name:"ShoppingForm",
	data() {
		return {
			item: {
				id:0,
				type:"",
				price:0,
				count:0			
			}
		}
	},
	methods: {
		addToList:function() {
			this.$emit("add-to-list",this.item);
			this.item = {
				id:0,
				type:"",
				price:0,
				count:0			
			}
		}
	}
}

</script>

// react/hooks-1-usestate/src/components/ShoppingForm.js
import React,{useState} from 'react';
import {Form,Button} from 'semantic-ui-react';

const ShoppingForm = ({addToList}) => {

	const [state,setState] = useState({
		type:"",
		price:0,
		count:0,
		id:0
	})
	
	const onChange = (event) => {
		setState({
			...state,
			[event.target.name]:event.target.value
		})
	}
	
	const onSubmit = (event) => {
		event.preventDefault();
		addToList(state);
	}
	
	return (
		<Form onSubmit={onSubmit}>
			<Form.Field>
				<label htmlFor="type">Type</label>
				<input type="text"
					   name="type"
					   onChange={onChange}
					   value={state.type}/>
			</Form.Field>
			<Form.Field>
				<label htmlFor="price">Price</label>
				<input type="number"
					   name="price"
					   onChange={onChange}
					   value={state.price}/>
			</Form.Field>
			<Form.Field>
				<label htmlFor="count">Count</label>
				<input type="number"
					   name="count"
					   onChange={onChange}
					   value={state.count}/>
			</Form.Field>
			<Button type="submit">Add</Button>
		</Form>
	)
	
}

export default ShoppingForm;
